Repository githubschool/tough-crowd, pull requests merged in 2020-05, with the labels that each got.

#12 msambam changes caption
  _posts/0000-01-07-msambam.md
Labels: enhancement

#14 beardofedu changes caption
  _posts/0000-01-23-beardofedu.md
Labels: enhancement

#15 Updated my caption
  _posts/0000-01-03-nikkoboy09.md
Labels: enhancement

#20 Updated aarontransue slide caption
  _posts/0000-01-12-aarontransue.md
Labels: enhancement

#25 Nickpender caption
  _posts/0000-01-14-NickPender.md
Labels: documentation

#24 updating slide
  _posts/0000-01-13-prbhasker.md
Labels: enhancement

#22 leroye123-caption change
  _posts/0000-01-20-leroye123.md
Labels: documentation, enhancement

#19 first check-in - edited
  _posts/0000-01-11-josepher79.md
  _posts/0000-01-22-josepher79.md
Labels: enhancement, question
